export const USER_ADD_REQUESTED = "USER_ADD_REQUEST"
export const USER_ADD_SUCCESSED = "USER_ADD_SUCCESSED"
export const USER_ADD_FAILD = "USER_ADD_FAILD"

export const USER_FETCH_REQUESTED = "USER_FETCH_REQUEST"
export const USER_FETCH_SUCCESSED = "USER_FETCH_SUCCESSED" 
export const USER_FETCH_FAILD = "USER_FETCH_FAILD"

export const USER_UPDATE_REQUESTED = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESSED = "USER_UPDATE_SUCCESSED"
export const USER_UPDATE_FAILD = "USER_UPDATE_FAILD"

export const USER_DELETE_REQUESTED = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESSED = "USER_DELETE_SUCCESSED"
export const USER_DELETE_FAILD = "USER_DELETE_FAILD"
